### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by MatthieuDartiailh** [MatthieuDartiailh/enaml#10]
Supporting python 3.6 requires to:
- the new format of the bytecode ie wordcode (note that some updates are needed to wbyteplay to get things to work)
- ~~the changes made to the bytecode describing function call which implies to modify the tracer code and potentially manually generated code calling function.~~ Actually tracing only look at CALL_FUNCTION so no problem there and there is a single occurrence of CALL_FUNCTION_VAR which is easily fixed
- changes to the grammar : 
  - asynchronous comprehension and generator are now allowed and lead to the addition of is_async argument to the comprehension node

So far it is all what I am sure about

**Comment by ghost** [comment]
Is this a fork of enaml that is maintained independently?

**Comment by MatthieuDartiailh** [comment]
It is my persornal fork on which I have developped (starting from others work) support for python 3 and recently pyqt5. I have opened pull requests againt the original repo to merge those changes but as the author @sccolbert is very busy it is not clear if or when it may happen.

**Comment by ghost** [comment]
> but as the author @sccolbert is very busy it is not clear if or when it may happen.

I suspected that. Personally I really like the concept of enaml but what worries me is the prospect of forward-incompatibility, given that bytecode is defined as implementation-specific. I would feel much more comfortable if enaml were working on abstract syntax trees, but I'm not sure that's possible.

**Comment by sccolbert** [comment]
@xoviat the AST is just as ill-defined as the bytecode, and is subject to change between versions. The way to solve this is with a change to how Atom fundamentally works, so that bytecode injection and/or AST parsing would not be required. I'm not sure what the appetite for that would be, particularly given how the web seems to be taking over the world (and my time!!!).

**Comment by MatthieuDartiailh** [comment]
closed by #11
