### ISSUE TITLE
Can't import enaml.signaling

### ISSUE THREAD

**Issue by ericdill** [MatthieuDartiailh/enaml#2]
Hi Matthieu,

Thanks so very much for your work on python 3 compatibility for enaml.  It is so very much appreciated!  I am trying to give your py3 enaml branch some real world testing and an running into an issue with the enaml/src/signaling.cpp module.  After building enaml in a python 3.4 or 3.5 environment I get an ImportError when enaml.signaling is imported:

```
$ python -c "import enaml.signaling"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'weakmethod'
```

I discovered this when trying to build conda packages for your python 3 compatibility work on kiwisolver, atom and enaml.  Those conda packages are located [here](https://github.com/NSLS-II/auto-build-tagged-recipes/tree/enaml-stack-py3/enaml-stack) if you are curious.

Thanks again for your efforts on this!

**Comment by MatthieuDartiailh** [comment]
Sorry for the branch mess but you should use the parser23 branch. I plan to cleanup soon as I will need some conda packages myself.
Can you give it a try ?

**Comment by MatthieuDartiailh** [comment]
I can reproduce even on parser23.
I will try to fix it ASAP.

**Comment by MatthieuDartiailh** [comment]
Fixed in d53580a714a66968dfa86fbe712cd52f1d1ab306.

**Comment by ericdill** [comment]
Ah yes I should have said that I am using the parser23 branch. Sorry!  Thanks for the quick fix!  I'll try again to build a conda package for this and report back.

**Comment by ericdill** [comment]
Looks like the conda package is building successfully. I'll try to run our GUI with the python 3 compatible libraries and report back. Thanks!

**Comment by gabrielcnr** [comment]
Could you please kindly provide the conda recipe so I can try to build it for Mac OS X and Win64? Thanks.

**Comment by ericdill** [comment]
Here are the three conda recipes that you need. I am planning on putting these into conda forge and maintaining them once these Python 3 branches are all merged in and tagged

https://github.com/NSLS-II/auto-build-tagged-recipes/tree/master/enaml-stack

**Comment by ericdill** [comment]
@gabrielcnr did that give you what you needed?
