### ISSUE TITLE
Unicode can't be used in .enaml files

### ISSUE THREAD

**Issue by kiwi0fruit** [MatthieuDartiailh/enaml#20]
Unicode strings do not work when are in *.enaml files (broken chars are shown instead).
But when we declare them in .py file and import they show correctly. Simple example:
```
Label:
    text = "Here should be alpha betta gamma: αβγ"
```
On Windows 7 x64, Python 3.6 x64, Enaml v0.10.0 (actually this bug is present on any Python 3 enaml version).

**Comment by MatthieuDartiailh** [comment]
I will try to take a look next week. The handling this was never really obvious to me so it may well be incorrect in this case.

**Comment by MatthieuDartiailh** [comment]
I have a fix for that but it will take me some time to properly format and add tests to avoid further regressions. It will be merged as part of #18 . Thanks again for the report.

**Comment by MatthieuDartiailh** [comment]
Would you care to test #18 ? I believe it should fix your issue.

**Comment by MatthieuDartiailh** [comment]
This is now fixed by #18. I will try to make a new release (0.10.1.dev) soon
