### ISSUE TITLE
Work around for mro issues with Pyside now does not work

### ISSUE THREAD

**Issue by kiwi0fruit** [MatthieuDartiailh/enaml#22]
There is a [Pyside-Enaml bug](https://github.com/nucleic/enaml/pull/111). It had a working workarounds on python 2.7. Now they do not work for some reason.

Both patches proposed ([1st](https://github.com/nucleic/enaml/pull/111/commits/f5784849ec0b47bbffa978569fe6723523ece61e) and [2nd](https://github.com/frmdstryr/enaml/commit/c9cebd72ac6152217ac8a0689a882576c240ba31)) do not fix the problem on Enaml 0.10.0 (Python 3 version from `conda install -c ecpy enaml`).

The test enaml code:
```
PushButton:
    text = "Test PySide-Enaml bug"
    clicked ::
        information(self, "Testing", "If you see this then presumably PySide-Enaml bug was patched.\n" +
                    "But it still can be broken if Python hangs after pressing OK.")
```
Before patches applied message box does not appear and python shows long error messages. After patch applied the message box appear, but when I close it pressing OK Windows says that python.exe stopped working. After I close it i get only `Process finished with exit code -1073741819 (0xC0000005)`.

Windows 7 x64 Miniconda python. Checked with Python 3.6 x64, PySide from `conda install -c conda-forge pyside` and with Python 3.4 win32, Pyside from `pip install pyside`.

**Comment by MatthieuDartiailh** [comment]
Pyside was never officially supported and now that pyside2 is under way for qt5, I do not have a strong drive to spend time on this. Sorry.
If you come up with a solution I will nonetheless be happy to review a PR.

**Comment by kiwi0fruit** [comment]
Additioanl info: these two patches also do not work on Enaml 0.10.0 at Python 2.7 (same behaviour as described above). But they do work on Enaml 0.9.8 at Python 2.7.

This may indicate that some instability was introduced to Enaml python 3 version (Error code 0xc0000005 means access violation).

**Comment by MatthieuDartiailh** [comment]
I will try to give a look. Thanks for the details.

**Comment by kiwi0fruit** [comment]
Actually this is most likely to be the PySide fault. A year ago I was trying to get realtime video in Qt widget (no Enaml, may be it was just qtpy). Everything worked fine on PyQt but on PySide there were lags and damage of frames. And it looked like it's somekind of memory bugs. So access violation is a thing that we can expect from PySide.

But at the same time the patches above work fine on Enaml 0.9.8@py2.7 but do not on 0.10.0@py2.7. So there is still some room for speculations.
