### ISSUE TITLE
Can't compile on FreeBSD 10.3 w/ clang or gcc

### ISSUE THREAD

**Issue by yggdr** [MatthieuDartiailh/enaml#3]
Hi,

I can't get the python3 version to compile on FreeBSD 10.3
The 2.7 version I installed via pip seems to work. I attached the output of
python3.5 setup.py install --user
and
CC=gcc python3.5 setup.py install --user

[OUTPUT.TXT](https://github.com/MatthieuDartiailh/enaml/files/364617/OUTPUT.TXT)
[OUTPUT.gcc.TXT](https://github.com/MatthieuDartiailh/enaml/files/364618/OUTPUT.gcc.TXT)

Thank you for your effort of porting enaml to python3!

**Comment by MatthieuDartiailh** [comment]
Thanks for the report. Could you tell me what branch you tried to install ?
One thing is that you should install kiwisolver from github master and atom from my fork (branch py23) before installing enaml otherwise setuptools will use pip to install those and find non-python3 compatible versions.

**Comment by MatthieuDartiailh** [comment]
Closing for lack of answer.
